config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'active' => 'home#active'
  get 'info' => 'home#info'
  get 'service' => 'home#service'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def active

  end

  def info

  end

  def service

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_introduce.html.erb
<!-- banner start -->
<!-- ================ -->
<div id="banner" class="banner">

  <div class="banner-caption">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn">
          <h1 class="text-center">We are <span>Worthy</span></h1>
          <p class="lead text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos debitis provident nulla illum minus enim praesentium repellendus ullam cupiditate reiciendis optio voluptatem, recusandae nobis quis aperiam, sapiente libero ut at.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- banner end -->

app/views/home/active.html.erb
<!-- section start -->
<!-- ================ -->
<div class="section clearfix object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 id="about" class="title text-center">About <span>Worthy</span></h1>
        <p class="lead text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta officia, aspernatur.</p>
        <div class="space"></div>
        <div class="row">
          <div class="col-md-6">
            <img src="images/section-image-1.png" alt="">
            <div class="space"></div>
          </div>
          <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi adipisci illo, voluptatum ipsam fuga error commodi architecto, laudantium culpa tenetur at id, beatae placeat deserunt iure quas voluptas fugit eveniet.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo ducimus explicabo quibusdam temporibus deserunt doloremque pariatur ea, animi a. Delectus similique atque eligendi, enim vel reiciendis deleniti neque aliquid, sit?</p>
            <ul class="list-unstyled">
              <li><i class="fa fa-caret-right pr-10 text-colored"></i> Lorem ipsum dolor sit amet</li>
              <li><i class="fa fa-caret-right pr-10 text-colored"></i> Reiciendis deleniti neque aliquid</li>
              <li><i class="fa fa-caret-right pr-10 text-colored"></i> Ipsam fuga error commodi</li>
              <li><i class="fa fa-caret-right pr-10 text-colored"></i> Lorem ipsum dolor sit amet</li>
              <li><i class="fa fa-caret-right pr-10 text-colored"></i> Dignissimos molestiae necessitatibus</li>
            </ul>
          </div>
        </div>
        <div class="space"></div>
        <h2>Becessitatibus quae beatae possimus ullam</h2>
        <div class="row">
          <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi adipisci illo, voluptatum ipsam fuga error commodi architecto, laudantium culpa tenetur at id, beatae placeat deserunt iure quas voluptas fugit eveniet.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo ducimus explicabo quibusdam temporibus deserunt doloremque pariatur ea, animi a. Delectus similique atque eligendi, enim vel reiciendis deleniti neque aliquid, sit?</p>
            <p>Vitae dolores quam magnam accusantium nam, voluptatibus expedita delectus, dolorum odio magni ut nemo nihil ex earum pariatur molestias velit eveniet, facere autem saepe aut. Ut minima itaque porro facere. Cumque vitae autem, dignissimos molestiae necessitatibus culpa aliquam deleniti soluta sunt voluptatibus tenetur, unde dolorem eligendi doloribus quibusdam facere totam. Possimus atque deserunt numquam aliquam magnam, facilis officiis illo alias ipsa voluptas laborum, praesentium eveniet nobis velit voluptatem odio eligendi, corporis et iste distinctio! Repellendus, id, ad.</p>
          </div>
          <div class="col-md-6">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      Collapsible Group Item #1
                    </a>
                  </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher.
                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                  <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Collapsible Group Item #2
                    </a>
                  </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="panel-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingThree">
                  <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      Collapsible Group Item #3
                    </a>
                  </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                  <div class="panel-body">
                    Richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- section end -->

app/views/home/index.html.erb
<%= render 'introduce' %>

<%= render 'product' %>

app/views/home/info.html.erb
<!-- section start -->
<!-- ================ -->
<div class="section translucent-bg pb-clear">
  <div class="container object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn">
    <h1 id="clients" class="title text-center">Clients</h1>
    <div class="space"></div>
    <div class="row">
      <div class="col-md-4">
        <div class="media testimonial">
          <div class="media-left">
            <img src="images/testimonial-1.png" alt="">
          </div>
          <div class="media-body">
            <h3 class="media-heading">You are Amazing!</h3>
            <blockquote>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo.</p>
              <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="media testimonial">
          <div class="media-left">
            <img src="images/testimonial-2.png" alt="">
          </div>
          <div class="media-body">
            <h3 class="media-heading">Yeah!</h3>
            <blockquote>
              <p>Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus.</p>
              <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="media testimonial">
          <div class="media-left">
            <img src="images/testimonial-3.png" alt="">
          </div>
          <div class="media-body">
            <h3 class="media-heading">Thank You!</h3>
            <blockquote>
              <p>Aperiam consequatur quo quis exercitationem reprehenderit suscipit iste placeat.</p>
              <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="media testimonial">
          <div class="media-left">
            <img src="images/testimonial-2.png" alt="">
          </div>
          <div class="media-body">
            <h3 class="media-heading">Thank You!</h3>
            <blockquote>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo.</p>
              <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="media testimonial">
          <div class="media-left">
            <img src="images/testimonial-3.png" alt="">
          </div>
          <div class="media-body">
            <h3 class="media-heading">Amazing!</h3>
            <blockquote>
              <p>Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus.</p>
              <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="media testimonial">
          <div class="media-left">
            <img src="images/testimonial-1.png" alt="">
          </div>
          <div class="media-body">
            <h3 class="media-heading">Best!</h3>
            <blockquote>
              <p>Aperiam consequatur quo quis exercitationem reprehenderit suscipit iste placeat.</p>
              <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- section start -->
  <!-- ================ -->
  <div class="translucent-bg blue">
    <div class="container">
      <div class="list-horizontal">
        <div class="row">
          <div class="col-xs-2">
            <div class="list-horizontal-item">
              <img src="images/client-1.png" alt="client">
            </div>
          </div>
          <div class="col-xs-2">
            <div class="list-horizontal-item">
              <img src="images/client-2.png" alt="client">
            </div>
          </div>
          <div class="col-xs-2">
            <div class="list-horizontal-item">
              <img src="images/client-3.png" alt="client">
            </div>
          </div>
          <div class="col-xs-2">
            <div class="list-horizontal-item">
              <img src="images/client-4.png" alt="client">
            </div>
          </div>
          <div class="col-xs-2">
            <div class="list-horizontal-item">
              <img src="images/client-5.png" alt="client">
            </div>
          </div>
          <div class="col-xs-2">
            <div class="list-horizontal-item">
              <img src="images/client-6.png" alt="client">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- section end -->
</div>
<!-- section end -->



<!-- section start -->
<!-- ================ -->
<div class="default-bg space">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1 class="text-center">10000+ Happy Clients!</h1>
      </div>
    </div>
  </div>
</div>
<!-- section end -->

app/views/home/service.html.erb
<!-- section start -->
<!-- ================ -->
<div class="section translucent-bg">
  <div class="container object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn">
    <h1 id="services" class="text-center title">Worthy Services</h1>
    <div class="space"></div>
    <div class="row">
      <div class="col-sm-6">
        <div class="media">
          <div class="media-body text-right">
            <h4 class="media-heading">Service 1</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
          <div class="media-right">
            <i class="fa fa-cog"></i>
          </div>
        </div>
        <div class="media">
          <div class="media-body text-right">
            <h4 class="media-heading">Service 2</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
          <div class="media-right">
            <i class="fa fa-check"></i>
          </div>
        </div>
        <div class="media">
          <div class="media-body text-right">
            <h4 class="media-heading">Service 3</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
          <div class="media-right">
            <i class="fa fa-desktop"></i>
          </div>
        </div>
        <div class="media">
          <div class="media-body text-right">
            <h4 class="media-heading">Service 4</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
          <div class="media-right">
            <i class="fa fa-users"></i>
          </div>
        </div>
      </div>
      <div class="space visible-xs"></div>
      <div class="col-sm-6">
        <div class="media">
          <div class="media-left">
            <i class="fa fa-leaf"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Service 5</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
        </div>
        <div class="media">
          <div class="media-left">
            <i class="fa fa-area-chart"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Service 6</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
        </div>
        <div class="media">
          <div class="media-left">
            <i class="fa fa-child"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Service 7</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
        </div>
        <div class="media">
          <div class="media-left">
            <i class="fa fa-codepen"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Service 8</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure aperiam consequatur quo quis exercitationem reprehenderit dolor vel ducimus, voluptate eaque suscipit iste placeat.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<div class="default-bg space blue">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1 class="text-center">Let's Work Together!</h1>
      </div>
    </div>
  </div>
</div>
<!-- section end -->

app/views/layouts/_footer.html.erb
<!-- footer start -->
<!-- ================ -->
<footer id="footer">

  <!-- .footer start -->
  <!-- ================ -->
  <div class="footer section">
    <div class="container">
      <h1 class="title text-center" id="contact">Contact Us</h1>
      <div class="space"></div>
      <div class="row">
        <div class="col-sm-6">
          <div class="footer-content">
            <p class="large">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel nam magnam natus tempora cumque, aliquam deleniti voluptatibus voluptas. Repellat vel, et itaque commodi iste ab, laudantium voluptas deserunt nobis.</p>
            <ul class="list-icons">
              <li><i class="fa fa-map-marker pr-10"></i> One infinity loop, 54100</li>
              <li><i class="fa fa-phone pr-10"></i> +00 1234567890</li>
              <li><i class="fa fa-fax pr-10"></i> +00 1234567891 </li>
              <li><i class="fa fa-envelope-o pr-10"></i> your@email.com</li>
            </ul>
            <ul class="social-links">
              <li class="facebook"><a target="_blank" href="https://www.facebook.com/pages/HtmlCoder/714570988650168"><span>QQ</span></a></li>
              <li class="twitter"><a target="_blank" href="https://twitter.com/HtmlcoderMe"><span>WeXin</span></a></li>
              <li class="googleplus"><a target="_blank" href="http://plus.google.com"><span>WeiBo</span></a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="footer-content">
            <form role="form" id="footer-form">
              <div class="form-group has-feedback">
                <label class="sr-only" for="name2">Name</label>
                <input type="text" class="form-control" id="name2" placeholder="Name" name="name2" required="">
                <i class="fa fa-user form-control-feedback"></i>
              </div>
              <div class="form-group has-feedback">
                <label class="sr-only" for="email2">Email address</label>
                <input type="email" class="form-control" id="email2" placeholder="Enter email" name="email2" required="">
                <i class="fa fa-envelope form-control-feedback"></i>
              </div>
              <div class="form-group has-feedback">
                <label class="sr-only" for="message2">Message</label>
                <textarea class="form-control" rows="8" id="message2" placeholder="Message" name="message2" required=""></textarea>
                <i class="fa fa-pencil form-control-feedback"></i>
              </div>
              <input type="submit" value="Send" class="btn btn-default">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- .footer end -->

  <!-- .subfooter start -->
  <!-- ================ -->
  <div class="subfooter">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p class="text-center">Copyright © 2014 Worthy by <a target="_blank" href="http://htmlcoder.me">HtmlCoder</a>.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- .subfooter end -->

</footer>
<!-- footer end -->

app/views/layouts/_header.html.erb
<!-- vedio background -->
<video autoplay="" loop="" poster="polina.jpg" id="bgvid">

  <source src="video/polina.webm" type="video/webm">

  <source src="video/polina.mp4" type="video/mp4">

</video>
<!-- scrollToTop -->
<!-- ================ -->
<div class="scrollToTop"><i class="icon-up-open-big"></i></div>

<!-- header start -->
<!-- ================ -->
<header class="header fixed clearfix navbar navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-md-4">

        <!-- header-left start -->
        <!-- ================ -->
        <div class="header-left clearfix">

          <!-- logo -->
          <div class="logo smooth-scroll">
            <a href="#banner"><img id="logo" src="images/mystore.png" alt="mystore"></a>
          </div>

          <!-- name-and-slogan -->
          <div class="site-name-and-slogan smooth-scroll">
            <div class="site-name"><a data-toggle="collapse" href="#cart">MyStroe</a></div>
            <div class="site-slogan">Free Bootstrap Theme by <a target="_blank" href="http://htmlcoder.me">HtmlCoder</a></div>
          </div>

        </div>
        <!-- header-left end -->

      </div>
      <div class="col-md-8">

        <!-- header-right start -->
        <!-- ================ -->
        <div class="header-right clearfix">

          <!-- main-navigation start -->
          <!-- ================ -->
          <div class="main-navigation animated">

            <!-- navbar start -->
            <!-- ================ -->
            <nav class="navbar navbar-default" role="navigation">
              <div class="container-fluid">

                <!-- Toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse scrollspy smooth-scroll" id="navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%= link_to '主页', root_path %>
                    </li>
                    <li>
                      <%= link_to '活动', active_path %>
                    </li>
                    <li>
                      <%= link_to '服务', service_path %>
                    </li>
                    <li>
                      <%= link_to '用户', info_path %>
                    </li>
                    <li><a data-toggle="collapse" data-target="#cart" id="cartcontrol">Cart</a></li>
                  </ul>
                </div>
                <div class="cart">

                  <!-- <a data-toggle="collapse" href="#cart">Cart</a> -->
                </div>
              </div>
            </nav>
            <!-- navbar end -->

          </div>
          <!-- main-navigation end -->

        </div>
        <!-- header-right end -->

      </div>
    </div>
  </div>
  <!-- cart -->

  <div class="panel-collapse collapse" id="cart">
    <div class="panel-body">
      <div class="container">
        <h1>ShopCart</h1>
      </div>
    </div>
  </div>
</header>
<!-- header end -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dian</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Mobile Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico">

  <!-- Web Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700,300&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Raleway:700,400,300" rel="stylesheet" type="text/css">

  <!-- Font Awesome CSS -->
  <link href="fonts/font-awesome/css/font-awesome.css" rel="stylesheet">

  <!-- Plugins -->
  <link href="css/animations.css" rel="stylesheet">

  <!-- Worthy core CSS file -->
  <link href="css/style.css" rel="stylesheet">

  <!-- Custom css -->
  <link href="css/custom.css" rel="stylesheet">
</head>
<body class="no-trans scroll-spy fixed-header-on">

<%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>
<script type="text/javascript" src="plugins/jquery.min.js"></script>
<script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>

<!-- Modernizr javascript -->
<script type="text/javascript" src="plugins/modernizr.js"></script>

<!-- Isotope javascript -->
<script type="text/javascript" src="plugins/isotope/isotope.pkgd.min.js"></script>

<!-- Backstretch javascript -->
<script type="text/javascript" src="plugins/jquery.backstretch.min.js"></script>

<!-- Appear javascript -->
<script type="text/javascript" src="plugins/jquery.appear.js"></script>

<!-- Initialization of Plugins -->
<script type="text/javascript" src="js/template.js"></script>

<!-- Custom Scripts -->
<script type="text/javascript" src="js/custom.js"></script>
</body>

</html>